### ISSUE TITLE
UI: Long report name overlaps the borders

### ISSUE THREAD

**Issue by nnobelis** [eclipse-apoapsis/ort-server#1548]
![Untitled](https://github.com/user-attachments/assets/15f6903f-1351-4ddb-9edf-6cf5fb588d8b)

See screenshot: when the report name is really long, it overlaps the border around it.

**Comment by sschuberth** [comment]
Which report type is that, a custom HTML report?

**Comment by Etsija** [comment]
@nnobelis please can you check if #1557 fix is acceptable for you at this phase? When I was testing, even the hard-breaking `break-all` TailwindCSS class didn't work, so I resorted to using `truncate` instead, which just cuts the end with ellipsis.

Because I didn't have your example filename to test with, I did it like this. If that's not acceptable solution, we need to come up with a better one.

**Comment by nnobelis** [comment]
@Etsija Unfortunately the fix missed the release window we had. 
Hence, I'll give you the confirmation after the next release.

**Comment by nnobelis** [comment]
@Etsija 

![Untitled](https://github.com/user-attachments/assets/ade964c6-260b-409a-9ef5-bd72022442ac)

I can confirm the bug is fixed :+1:
