### ISSUE TITLE
Change the web site title according to the viewed org / product / repo

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#1573]
With multiple browser tabs open, it's confusing that they all are called just "ORT Server". It would be great if there was a prefix added depending on the org / product / repo that's currently viewed.

**Comment by Etsija** [comment]
It's currently specified statically [here](https://github.com/eclipse-apoapsis/ort-server/blob/main/ui/index.html). Need to inspect ways to change it dynamically; [there are ways](https://stackoverflow.com/questions/74759501/how-can-i-dynamically-change-title-in-vite-react) to do that.

**Comment by Etsija** [comment]
[Documenting a bit further](https://github.com/TanStack/router/discussions/1056) for whoever will do this: there is probably a simple way to do this dynamically by a self-written hook and a document wrapper component.

**Comment by Etsija** [comment]
@sschuberth Something like this? I'm wondering whether we actually need to show "ORT Server" in the title on those subpages, because there's already the server icon? Long titles are cut from the end, and leaving "ORT Server" out from the title would make it a bit more readable.

Anything more you'd like to see in the title, considering it should probably be kept quite tight?

![Screenshot from 2024-12-09 07-34-08](https://github.com/user-attachments/assets/e9a4dc8d-4331-4e81-a950-c47ec217e91f)
