### ISSUE TITLE
Git config file provider: where to do checkout to local folder?

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#395]
I am currently implementing a git config file provider, which is otherwise similar to local config file provider, but first checks out (downloads) a Git configuration repository, then stores it to local folder (in Docker Compose environment).

I have written the provider to comply with [this interface](https://github.com/eclipse-apoapsis/ort-server/blob/3d45759874a81cb618ef07cfff1c76a3d23f391d/config/spi/src/main/kotlin/ConfigFileProvider.kt#L24-L58), but am unsure where the checkout (which is done by using `initWorkingTree()` and `updateWorkingTree()` from ORT `downloader.VersionControlSystem`) should be done.

Currently I have put the checkout procedure as a function call in `resolveContext()`, because the same method returns the commit SHA of the head of checked-out branch as the context. On top of the unit tests of local config file provider, I have written some of my own which use a "synthetic" configuration repository that doubleopen-project hosts on GitHub. Using the unit tests, I have verified that the provider is able to
- resolve the context properly for different branches
- see, list and read the files in the repository, be it direct files, symlinks, files from a submodule or symlinks to files from a submodule

To verify that I am on the right path (or conclude that I am not), I'd like to ask specifically: am I correct that such a git config file provider
- is created _once_ ie. when the server is started
- context is resolved just before the ORT Run
- as a consequence, the config files are checked out to eg. `/mnt/git-config` once per ORT Run and can be referred to using their paths inside the repository - which can be passed to the ORT Run in job configurations?

As I've not done anything like this before, I can very well be wrong in my assumptions. At least I've been able to verify the basic functionality of such a provider, the way I see it could behave.

**Comment by Etsija** [comment]
For reference, here's my current implementation, which you are free to comment:
https://github.com/doubleopen-project/ort-server/tree/do-720-read-evaluator-config

Please note that it is _not_ intended to be PR-ready yet.

**Comment by mnonnenmacher** [comment]
> Currently I have put the checkout procedure as a function call in `resolveContext()`, because the same method returns the commit SHA of the head of checked-out branch as the context.

`resolveContext()` is called only once by the config worker. All other workers will then use the same context to ensure that the used config files are consistent. What exactly the `context` is depends on the provider implementation. In case of a Git config file provider, the context would be the Git revision (SHA1 not branch or tag name). This ensures that all workers use the configuration files from the same Git revision.

The input for `resolveContext()` is the `jobConfigContext` from `CreateOrtRun`. As this property is nullable, the provider also must define a default. For a Git provider it makes most sense to use `"main"` as the default, like the `GitHubConfigFileProvider` does.

For example, the `GitHubConfigFileProvider` expects the `jobConfigContext` to be a branch name and uses the GitHub API to figure out what the commit SHA1 for the provided branch is. Your Git provider should do the same by checking out the repository with `initWorkingTree()` and `updateWorkingTree()` like you already do. Convienently `updateWorkingTree()` returns the revision which you can then return as the resolved context (similar to the `OrtConfigPackageCurationProvider` in ORT):

```kotlin
val revision = updateWorkingTree(...).getOrThrow()
return Context(revision)
```

The other functions in the interface like `getFile` have `context` argument which contains the resolved context and should use that to clone this revision of the Git repository by calling `updateWorkingTree(workingTree, context.name)`. To not clone the repository again on each call, you should make a helper function which only clones the repository only if it was not already cloned before.

> To verify that I am on the right path (or conclude that I am not), I'd like to ask specifically: am I correct that such a git config file provider
> 
>     * is created _once_ ie. when the server is started

Yes


>     * context is resolved just before the ORT Run

Yes, by the config worker which is the first step in each ORT run.

>     * as a consequence, the config files are checked out to eg. `/mnt/git-config` once per ORT Run and can be referred to using their paths inside the repository - which can be passed to the ORT Run in job configurations?

Almost, but the repository needs to be cloned once by each worker, because they run in different pods.

Regarding the directory, you could either use a hardcoded one like `/home/.ort/server/git-config` or create a temporary directory with the Kotlin function `createTempDirectory` (or use ORT's version `createOrtTempDir`). I think I would use a temporary directory to avoid any conflicts and because it only exists for the lifetime of a job anyway.

**Comment by mnonnenmacher** [comment]
> the GitHubConfigFileProvider expects the jobConfigContext to be a branch name and uses the GitHub API to figure out what the commit SHA1 for the provided branch is

In your case you don't need that limitation as `updateWorkingTree` accepts any valid Git revision like a branch name, tag, or SHA1.

**Comment by sschuberth** [comment]
> `resolveContext()` is called only once by the config worker.

To clarify: Once per what? I assume once per start of the server (and not once per job run or so).

> In case of a Git config file provider, the context would be the Git revision (SHA1 not branch or tag name).

Well, I guess the *input* `context` to `resolveContext()` could be a branch or tag name, but the *output* / returned context has to be a fixed SHA1.

> The input for `resolveContext()` is the `jobConfigContext` from CreateOrtRun.

As a remark, IMO the naming is suboptimal here. It would have been clearer if in the API `jobConfigContext` would have been called e.g. `configProviderContext`.

> Convienently `updateWorkingTree()` returns the revision which you can then return as the resolved context

I believe you can't, as `updateWorkingTree()` does *not* return the resolved revision, but whatever revision was used as the input, see [these tests](https://github.com/oss-review-toolkit/ort/blob/e20d80f0a0c92fb1d1da61fab577fe4a2fbdcd0c/plugins/version-control-systems/git/src/funTest/kotlin/GitFunTest.kt#L70-L82). Instead, you need to explicitly call `workingTree.getRevision()`.

> To not clone the repository again on each call, you should make a helper function which only clones the repository if it was not already cloned before.

@mnonnenmacher what do you tjhink about simply leveraging ORT core's [DefaultWorkingTreeCache](https://github.com/oss-review-toolkit/ort/blob/e20d80f0a0c92fb1d1da61fab577fe4a2fbdcd0c/scanner/src/main/kotlin/utils/WorkingTreeCache.kt#L56) for that? (Which I'd in that context also move from the scanner to the downloader.)

**Comment by mnonnenmacher** [comment]
> > `resolveContext()` is called only once by the config worker.
> 
> To clarify: Once per what? I assume once per start of the server (and not once per job run or so).

Once per ORT run. The config context is specific to a single ORT run and is therefore resolved once at the beginning of each run.

> > In case of a Git config file provider, the context would be the Git revision (SHA1 not branch or tag name).
> 
> Well, I guess the _input_ `context` to `resolveContext()` could be a branch or tag name, but the _output_ / returned context has to be a fixed SHA1.

Correct.

> > The input for `resolveContext()` is the `jobConfigContext` from CreateOrtRun.
> 
> As a remark, IMO the naming is suboptimal here. It would have been clearer if in the API `jobConfigContext` would have been called e.g. `configProviderContext`.

I agree.

> > Convienently `updateWorkingTree()` returns the revision which you can then return as the resolved context
> 
> I believe you can't, as `updateWorkingTree()` does _not_ return the resolved revision, but whatever revision was used as the input, see [these tests](https://github.com/oss-review-toolkit/ort/blob/e20d80f0a0c92fb1d1da61fab577fe4a2fbdcd0c/plugins/version-control-systems/git/src/funTest/kotlin/GitFunTest.kt#L70-L82). Instead, you need to explicitly call `workingTree.getRevision()`.

Good to know, I didn't check the implementation.

> > To not clone the repository again on each call, you should make a helper function which only clones the repository if it was not already cloned before.
> 
> @mnonnenmacher what do you think about simply leveraging ORT core's [DefaultWorkingTreeCache](https://github.com/oss-review-toolkit/ort/blob/e20d80f0a0c92fb1d1da61fab577fe4a2fbdcd0c/scanner/src/main/kotlin/utils/WorkingTreeCache.kt#L56) for that? (Which I'd in that context also [move from the scanner to the downloader](https://github.com/oss-review-toolkit/ort/pull/8745).)

I think this only makes sense if the API of the working tree cache is easier to use than using `initWorkingTree` and `updateWorkingTree` directly, because each worker clones the repository once and throws it away afterward. At least that's true for a Kubernetes deployment where the workers run as Kubernetes jobs, in Docker Compose the workers keep running so using the cache might improve the performance.

**Comment by mnonnenmacher** [comment]
@Etsija Just in case this still helps you, the basic logic to avoid cloning the repository on each function call could look like this:

```kotlin
class GitConfigFileProvider {
  private var clonedRevision: String? = null
  private val dir = createTempDirectory()

  override fun getFile(context: Context, path: Path): InputStream {
    updateRepository(context.name)
    // code to read the file from `dir`
  }

  private fun updateRepository(val revision: String) {
    if (clonedRevision == revision) return
    // code to clone the provided revision to `dir`
  }
}
```
