### ISSUE TITLE
Links to routes do not work

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#435]
When opening a URL like `/organizations/1` or `/organizations/1/products/1/repositories/1/runs/1` the ui loads the organizations list instead of the requested page. This was tested in the Docker Compose setup. The issue only occurs if the ui was not previously loaded in the same browser tab.

**Comment by mmurto** [comment]
My first guess for what causes it is the auth checking [here](https://github.com/eclipse-apoapsis/ort-server/blob/4050644c1eedc39fbfa8bf022808b264c738c7b5/ui/src/app.tsx#L74). Quick look [at the documentation](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinRedirect) says that there's no way to specify the redirect URL for where it should return after signing in, but there could be something. If the problem is this, it could likely be solved if we used cookies for authentication (#178)

**Comment by mmurto** [comment]
> Quick look [at the documentation](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinRedirect) says that there's no way to specify the redirect URL for where it should return after signing in, but there could be something.

And there is something, as it actually should take `redirect_uri`. So **if** the auth check is the problem, using `redirect_uri` of the current path could make it work.

**Comment by mmurto** [comment]
> If the problem is this, it could likely be solved if we used cookies for authentication (#178)

For completion, this like would not be solved by only using cookies, even though it will probably change the redirect logic a bit.
