### ISSUE TITLE
Display configuration of finished jobs more nicely than raw JSON

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#644]
This

![image](https://github.com/eclipse-apoapsis/ort-server/assets/349154/6cf94eeb-e7aa-4827-826f-729eb30442a2)

should be a rendered as a collapsible tree (which only first level entries expanded by default).

At the same time values should be rendered in a meaningful way, i.e. entries with empty values should be omitted, and times should be converted to local time.

**Comment by mmurto** [comment]
I suggest that instead of a collapsible tree we use a description list or something structured, as the object is always known. Maybe something along the lines of [this example](https://ui.shadcn.com/blocks#dashboard-05):

![image](https://github.com/eclipse-apoapsis/ort-server/assets/2370887/63d82f2e-5f0b-43f8-9d6d-06fd6eccde8b)

**Comment by Etsija** [comment]
Can be closed with #917 merged.
