### ISSUE TITLE
Right-align the left-hand side menu

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#921]
On large screens there's a bug gap between the menu and the contents of the selected section:

![image](https://github.com/user-attachments/assets/9d3a387d-b89b-4957-9d88-02392bd545ac)

As the somewhat detaches the selected section from its content, we should improve that by right-aligning the menu to directly next to the left border of the content section. I.e. close the gap 😄

**Comment by Etsija** [comment]
That's not really how a sidebar works: it should always be staying on the left side, and the gap should be closed by moving/extending the main section to the left, just as in this view:

![Capture](https://github.com/user-attachments/assets/ab92fa54-e531-45ee-981e-1a731cf14c9c)

Otherwise, you'd see the sidebar jumping horizontally for every page where the main contents is aligned differently.

**Comment by lamppu** [comment]
So just to confirm before starting to work on this, is everyone on board with aligning the sidebar and the main section similarly to how a settings tab is rendered in GitHub? (Which to my understanding was the conclusion of an internal discussion we had yesterday)

![Näyttökuva (108)](https://github.com/user-attachments/assets/18771460-e325-4c02-b555-2d89b61e4aea)

**Comment by Etsija** [comment]
Yes I believe that was the way to do it. I'd first implement it on items pages (org, prod, repo), to collect feedback. The ORT run results page (main one) might be a bit of another case, as that will possibly be more dashboard-like.

**Comment by Etsija** [comment]
Can be closed with #965 merged now.
